version: '3'
services:
  prometheus:
    # 2.53 is LTS
    image: 'prom/prometheus:v2.53.1'
    restart: 'unless-stopped'
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: '300M'
        reservations:
          cpus: 0.2
          memory: '100M'
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml' # main config
      - './rules.yml:/etc/prometheus/rules.yml' # this feeds into alertmanager
    networks:
      - 'localprom'
    ports:
      - '9090:9090'
  blog-node-exporter:
    image: 'nginx/nginx-prometheus-exporter:1.1.0'
    restart: 'unless-stopped'
    deploy:
      resources:
        limits:
          cpus: 0.2
          memory: '100M'
        reservations:
          cpus: 0.1
          memory: '50M'
    networks:
      - 'localprom'
    ports:
      - '9113:9113'
    command:
      - '--nginx.scrape-uri=https://blog.tastybug.com/metrics'
  alert-manager:
    # no LTS available
    image: 'prom/alertmanager:v0.27.0'
    restart: 'unless-stopped'
    deploy:
      resources:
        limits:
          cpus: 0.2
          memory: '100M'
        reservations:
          cpus: 0.1
          memory: '50M'
    volumes:
      - './alertmanager.yml:/alertmanager/alertmanager.yml'
    networks:
      - 'localprom'
    ports:
      - '9093:9093'
  grafana:
    image: 'grafana/grafana:latest'
    restart: 'unless-stopped'
    deploy:
      resources:
        limits:
          cpus: 0.3
          memory: '200M'
        reservations:
          cpus: 0.2
          memory: '100M'
    volumes:
      - './grafana-storage:/var/lib/grafana'
    networks:
      - 'localprom'
    ports:
      - '3000:3000'
  blackbox:
    image: 'prom/blackbox-exporter:latest'
    restart: 'unless-stopped'
    deploy:
      resources:
        limits: 
          cpus: 0.2
          memory: '100M'
        reservations:
          cpus: 0.1
          memory: '30M'
    volumes:
      - './blackbox-config.yaml:/config/config.yaml'
    networks:
      - 'localprom'
    ports:
      - '9115:9115'
    command:
      - '--config.file=/config/config.yaml'
networks:
  localprom:
    driver: bridge
