version: '3'
services:
  prometheus:
    # 2.53 is LTS
    image: prom/prometheus:v2.53.1
    restart: 'unless-stopped'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 300M
        reservations:
          cpus: '0.2'
          memory: 100M
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml'
    networks:
      - localprom
    ports:
      - 9090:9090
networks:
  localprom:
    driver: bridge
