global:
  scrape_interval: 10s
rule_files:
  - rules.yml
alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alert-manager:9093
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - prometheus:9090
  - job_name: node
    static_configs:
      - targets:
        - blog-node-exporter:9113
  - job_name: grafana
    static_configs:
      - targets:
        - grafana:3000
# peek at curl 'http://localhost:9115/probe?target=blog.tastybug.com&module=http_2xx' | less
  - job_name: 'blackbox'
    metrics_path: '/probe'
    params:
      module: ['http_2xx']
    static_configs:
      - targets:
        - https://blog.tastybug.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'blackbox:9115'
  - job_name: 'blackbox_exporter'
    static_configs:
      - targets: 
        - 'blackbox:9115'  
